# Generated by Django 2.2.4 on 2024-04-25 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.TextField(default='some description'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.CharField(default='static/img/eye-cream.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='my_app.User'),
        ),
    ]
