# Generated by Django 2.2.4 on 2024-04-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20240428_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.TextField(),
        ),
    ]
